### ISSUE TITLE
Add a CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/GH-Spanish-Ranking#13]
This repository should have one CODE_OF_CONDUCT.md file

**Comment by iblancasa** [comment]
Look at https://github.com/iblancasa/GitHubCity/issues/126

**Comment by JoeBanks13** [comment]
Am reading the CODE_OF_CONDUCT.md file now :)

**Comment by ananya-gulati** [comment]
I can do this. Do you want the same file(as mentioned in the GitHubCity repo) to be added here?

**Comment by devophile** [comment]
I can do this. Do you want the same file(as mentioned in the GitHubCity repo) to be added here?

**Comment by iblancasa** [comment]
@devophile this file is Ok :+1: 

Thank you!
