### ISSUE TITLE
Add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by iblancasa** [iblancasa/GH-Spanish-Ranking#14]
It would be nice to have a contributing guide in the repository :v:

**Comment by jb3** [comment]
@iblancasa I'll take this one!

What are the important items to put in it?

**Comment by iblancasa** [comment]
@JoeBanks13 perfect!

Look at this one. Also, it should be consistent with #13

**Comment by jb3** [comment]
Anything you'd like me to change on #15?

**Comment by jb3** [comment]
Also appears your CI is malfunctioning...

**Comment by iblancasa** [comment]
I think it is Ok. Don't worry about the CI. It is failing because the encrypted variables can not be used in a PR.

Thank you!
